# Generated by Django 2.1.4 on 2019-01-17 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('errortype', models.CharField(max_length=100, null=True)),
                ('runtime', models.CharField(max_length=20, null=True)),
                ('memoryused', models.CharField(max_length=20, null=True)),
                ('filepath', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentfiles_assignment', to='assignment.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_assignment', to='assignment.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('errortype', models.CharField(max_length=100, null=True)),
                ('runtime', models.CharField(max_length=20, null=True)),
                ('memoryused', models.CharField(max_length=20, null=True)),
                ('filepath', models.CharField(max_length=100)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionfiles_submission', to='assignment.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_subject', to='subject.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_week', to='assignment.Week'),
        ),
    ]
