# Generated by Django 2.1.4 on 2019-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='status',
            new_name='isrunning',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='score',
            new_name='totalscore',
        ),
        migrations.AddField(
            model_name='submission',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission_files',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
