# Generated by Django 2.1.4 on 2019-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='week',
            name='lastdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
