# Generated by Django 2.1.4 on 2019-02-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='commentunread',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
