# Generated by Django 2.1.4 on 2019-01-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20190121_1718'),
        ('assignment', '0002_auto_20190118_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_subject', to='subject.Subject'),
        ),
    ]
