# Generated by Django 2.1.4 on 2019-01-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_inputfiles',
            field=models.IntegerField(null=True),
        ),
    ]
