# Generated by Django 2.1.4 on 2019-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignment_total_inputfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_files',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
