# Generated by Django 2.1.4 on 2019-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_assignment_files_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission_files',
            name='filepath',
            field=models.CharField(max_length=300),
        ),
    ]
