# Generated by Django 2.1.4 on 2019-01-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20190123_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='question',
            field=models.CharField(max_length=70000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='assignment_files',
            name='errortype',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assignment_files',
            name='filepath',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='assignment_files',
            name='memoryused',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assignment_files',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission_files',
            name='errortype',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submission_files',
            name='filepath',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission_files',
            name='memoryused',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
