# Generated by Django 2.1.4 on 2019-01-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20190126_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='totalscore',
            field=models.IntegerField(default=0),
        ),
    ]
