# Generated by Django 2.1.4 on 2019-01-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20190126_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='isdeleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='week',
            name='isdeleted',
            field=models.BooleanField(default=True),
        ),
    ]
