# Generated by Django 2.1.4 on 2019-01-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_auto_20190126_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='totalscore',
            field=models.IntegerField(default=0),
        ),
    ]
