# Generated by Django 2.1.4 on 2019-01-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_assignment_totalscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
