# Generated by Django 2.1.4 on 2019-01-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_submission_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='week',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
