# Generated by Django 2.1.4 on 2019-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
