# Generated by Django 2.1.4 on 2019-03-05 12:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0001_initial'),
        ('userprofile', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('maxscore', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_assignment', to='assignment.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_student', to='userprofile.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_subject', to='subject.Subject')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_week', to='assignment.Week')),
            ],
        ),
    ]
