# Generated by Django 2.1.4 on 2019-01-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20190126_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='is_active',
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
