# Generated by Django 2.1.4 on 2019-01-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20190127_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='is_removed',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='is_removed',
            new_name='is_active',
        ),
    ]
