# Generated by Django 2.1.4 on 2019-01-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('isRunning', models.CharField(max_length=20, null=True)),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions_all_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('errortype', models.CharField(max_length=100, null=True)),
                ('runtime', models.CharField(max_length=20, null=True)),
                ('memoryused', models.CharField(max_length=20, null=True)),
                ('filepath', models.CharField(max_length=100)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_submission', to='compilerApiApp.Submissions_all')),
            ],
        ),
    ]
