# Generated by Django 2.1.4 on 2019-01-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilerApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions_all_files',
            name='errortype',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submissions_all_files',
            name='filepath',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submissions_all_files',
            name='memoryused',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submissions_all_files',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
