# Generated by Django 2.1.4 on 2019-01-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilerApiApp', '0002_auto_20190126_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions_all_files',
            name='submission',
        ),
        migrations.DeleteModel(
            name='Submissions_all',
        ),
        migrations.DeleteModel(
            name='Submissions_all_files',
        ),
    ]
