# Generated by Django 2.1.4 on 2019-03-05 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('question', models.TextField(blank=True, null=True)),
                ('constraint', models.TextField(blank=True, null=True)),
                ('inputformat', models.TextField(blank=True, null=True)),
                ('outputformat', models.TextField(blank=True, null=True)),
                ('sampleinput', models.TextField(blank=True, null=True)),
                ('sampleoutput', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('total_inputfiles', models.IntegerField(default=0)),
                ('totalscore', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=None)),
                ('difficulty', models.CharField(max_length=30)),
                ('successful_submission', models.IntegerField(default=0)),
                ('total_submission', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Problem_files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('errortype', models.CharField(max_length=1000, null=True)),
                ('runtime', models.CharField(max_length=20, null=True)),
                ('memoryused', models.CharField(max_length=50, null=True)),
                ('filepath', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemfiles_problem', to='practice.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totalscore', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(max_length=50, null=True)),
                ('isrunning', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('commentunread', models.BooleanField(blank=True, default=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_problem', to='practice.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Submission_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission_files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('errortype', models.CharField(max_length=1000, null=True)),
                ('runtime', models.CharField(max_length=20, null=True)),
                ('memoryused', models.CharField(max_length=50, null=True)),
                ('filepath', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionfiles_submission', to='practice.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('problems', models.ManyToManyField(to='practice.Problem')),
            ],
        ),
    ]
