# Generated by Django 2.1.4 on 2019-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
