# Generated by Django 2.1.4 on 2019-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_problem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
