# Generated by Django 2.1.4 on 2019-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_problem_total_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='accuracy',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='problem',
            name='total_inputfiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem_files',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=30),
        ),
    ]
